### ISSUE TITLE
Image manipulation creates black images

### ISSUE THREAD

**Issue by Tekl** [typemill/typemill#211]
Hi,

I've some png images which will get black when using image manipulation. 

This is the original:
https://www.tekl.de/media/original/procontra.png

This is the black image calculated via `assets.image(post.meta.heroimage).resize(50,50).src()`:
https://www.tekl.de/media/custom/procontra-50x50.png

Stange is, that the scaled down live image is calculated correctly:
https://www.tekl.de/media/live/procontra.png

**Comment by trendschau** [comment]
probably the same here. I fixed the validation and in next release 1.4.0 the image manipulation works with `resize(100,100)` instead of `resize('100','100')`

**Comment by trendschau** [comment]
published with version 1.4.0 today

**Comment by Tekl** [comment]
The bug seems not be fixed. I still get sometimes black images like this one with resize(50,50):
![](https://tekl.de/media/custom/monterey-50x50.jpeg)

If I increase the pixels. It works well.
![](https://tekl.de/media/custom/monterey-75x75.jpeg) 75x75
![](https://tekl.de/media/custom/monterey-150x150.jpeg) 150x150

Here's the original:
![](https://tekl.de/media/live/monterey.jpeg)

**Comment by trendschau** [comment]
thank you, I will check it

**Comment by trendschau** [comment]
please reopen if this happens in version 2, too.
